from __future__ import annotations

"""SQLAlchemy ORM model for chat_conversations table.

One row per chat conversation. Owned by a single user inside a tenant.
Phase 8 Plan 02 — schema foundation.

D-20 column spec:
  id, tenant_id, created_at, updated_at  — from TenantScopedMixin
  user_id          — FK to users.id (owner of the conversation)
  title            — short human-readable label (TEXT NULL, generated by D-14 title generator)
  last_message_at  — TIMESTAMPTZ NOT NULL, updated on every new message (drives the
                     `ix_chat_conversations_tenant_user_last` index used by the sidebar
                     "recent conversations" query)
  archived         — BOOLEAN NOT NULL DEFAULT false (UI "Archive" toggle)

T-08-01 (Information Disclosure): inherits TenantScopedMixin so the Phase 1
`with_loader_criteria` event listener automatically filters every ORM select()
by tenant_id. Repositories (plan 08-04) layer explicit tenant validation on top
per defense-in-depth (LM-4).

D-22 (tenant isolation seam): the FK to users.id is NOT cross-tenant; users
themselves are tenant-scoped, and the Phase 1 filter on TenantScopedMixin
applies to `users` as well. The repository asserts user.tenant_id ==
conversation.tenant_id before returning rows.
"""

from datetime import datetime
from uuid import UUID

from sqlalchemy import Boolean, Text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base, TIMESTAMPTZ, TenantScopedMixin


class ChatConversation(Base, TenantScopedMixin):
    """One row per chat conversation, owned by a single user within a tenant.

    The `last_message_at` column drives the sidebar's "recent conversations"
    sort order — it's updated by the orchestrator (plan 08-04) every time a
    new message lands. The `archived` flag is a soft-hide toggle; rows are
    NEVER hard-deleted in MVP1 (D-deferred: GDPR hard-delete in Iteration 4).

    T-08-01 mitigation: TenantScopedMixin guarantees every query passes
    through the `with_loader_criteria` filter — no `select(ChatConversation)`
    can omit the tenant_id predicate.
    """

    __tablename__ = "chat_conversations"

    # FK to users.id — enforced at DDL level in migration 009; ORM declares the
    # column without a SQLAlchemy ForeignKey object per project convention
    # (see backend/app/models/insights/daily_insight.py — same pattern).
    user_id: Mapped[UUID] = mapped_column(PG_UUID(as_uuid=True), nullable=False)

    # Human-readable title (TEXT NULL) — generated lazily by the D-14 title
    # generator after the first assistant turn.
    title: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Drives the "recent conversations" sidebar sort. Initialized to created_at
    # at insert time by the migration's server_default=now(); refreshed by the
    # orchestrator on every appended message.
    last_message_at: Mapped[datetime] = mapped_column(TIMESTAMPTZ, nullable=False)

    # Soft-hide toggle — MVP1 has no hard delete. Default false at DDL level.
    archived: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
