"""Conversation request/response Pydantic DTOs for Phase 8 AI Chat.

D-15: archived column is part of the response shape (sidebar may filter).
D-13: created lazily — title generated by D-14 fire-and-forget Haiku call.
D-23: shapes consumed by 5 endpoints under /api/v1/chat/conversations.

Mirrors Phase 5 `daily_insight_schema.py` Pydantic v2 conventions:
  - `from __future__ import annotations`
  - Plain BaseModel (no orm_mode in v2 — repository converts to dicts)
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, Field


class ConversationOut(BaseModel):
    """Single conversation envelope returned by GET /chat/conversations.

    `title` may be None when the D-14 title generator hasn't completed yet.
    The frontend hot-swaps the sidebar label on the first SSE `done` event
    via TanStack Query invalidation.
    """

    id: UUID
    title: str | None
    created_at: datetime
    last_message_at: datetime
    archived: bool


class ConversationListOut(BaseModel):
    """List envelope for GET /chat/conversations."""

    conversations: list[ConversationOut]


class CreateConversationRequest(BaseModel):
    """Body for POST /chat/conversations.

    If `initial_message` is non-null, it's persisted as the first user message
    (so the client can immediately call POST /messages to stream the reply).
    """

    initial_message: str | None = Field(
        None,
        description="Optional first user message persisted on conversation creation.",
        max_length=10_000,
    )
