"""Create base tables: tenants, users, sync_runs, pipeline_runs.

Revision ID: 001
Revises: None
Create Date: 2026-05-21

Creates all 4 base tables required for Phase 1:
  - tenants: multi-tenant registry (no tenant_id — it IS the tenant)
  - users: tenant-scoped user accounts
  - sync_runs: ETL sync run tracking (Phase 2+ writes here)
  - pipeline_runs: daily analytics pipeline tracking (PIPE-04, Phase 3+ writes here)

All tenant-scoped tables have:
  - id UUID PRIMARY KEY (generated by application via uuid4)
  - tenant_id UUID NOT NULL REFERENCES tenants(id)
  - created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  - updated_at TIMESTAMPTZ NOT NULL DEFAULT now()

INFRA-02: TIMESTAMPTZ used (not TIMESTAMP) to avoid timezone ambiguity.
INFRA-03: tenant_id NOT NULL on every table except tenants (enforced here at DDL level
          in addition to the ORM-level with_loader_criteria enforcement in session.py).
PIPE-04: pipeline_runs table created in Phase 1 so Phase 3 can write to it immediately.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── tenants ──────────────────────────────────────────────────────────────
    # The tenant registry. Does NOT have a tenant_id column — it IS the tenant.
    # CLAUDE.md Core Principle #3 exception: tenants table omits tenant_id.
    op.create_table(
        "tenants",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("slug", sa.Text, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_unique_constraint("uq_tenants_slug", "tenants", ["slug"])

    # ── users ─────────────────────────────────────────────────────────────────
    # Tenant-scoped user accounts. tenant_id references tenants(id).
    op.create_table(
        "users",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.Text, nullable=False),
        sa.Column("hashed_password", sa.Text, nullable=False),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.text("true")),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], name="fk_users_tenant_id"),
    )
    op.create_unique_constraint("uq_users_email", "users", ["email"])
    op.create_index("ix_users_tenant_id", "users", ["tenant_id"])

    # ── sync_runs ─────────────────────────────────────────────────────────────
    # ETL sync run tracking. Phase 2 Celery tasks write here after each source sync.
    op.create_table(
        "sync_runs",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
        sa.Column("source", sa.Text, nullable=False),
        sa.Column("status", sa.Text, nullable=False),
        sa.Column("records_synced", sa.Integer, nullable=True),
        sa.Column("duration_ms", sa.Integer, nullable=True),
        sa.Column("error_msg", sa.Text, nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_sync_runs_tenant_id"
        ),
    )
    op.create_index("ix_sync_runs_tenant_id", "sync_runs", ["tenant_id"])

    # ── pipeline_runs ─────────────────────────────────────────────────────────
    # Daily analytics pipeline stage tracking (PIPE-04).
    # Phase 3+ Celery pipeline tasks write here after each stage completes.
    op.create_table(
        "pipeline_runs",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
        sa.Column("stage", sa.Text, nullable=False),
        sa.Column("status", sa.Text, nullable=False),
        sa.Column("records_processed", sa.Integer, nullable=True),
        sa.Column("duration_ms", sa.Integer, nullable=True),
        sa.Column("error_msg", sa.Text, nullable=True),
        sa.Column("run_date", sa.Date, nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_pipeline_runs_tenant_id"
        ),
    )
    op.create_index("ix_pipeline_runs_tenant_id", "pipeline_runs", ["tenant_id"])


def downgrade() -> None:
    # Drop in reverse creation order (respect FK constraints)
    op.drop_index("ix_pipeline_runs_tenant_id", table_name="pipeline_runs")
    op.drop_table("pipeline_runs")

    op.drop_index("ix_sync_runs_tenant_id", table_name="sync_runs")
    op.drop_table("sync_runs")

    op.drop_index("ix_users_tenant_id", table_name="users")
    op.drop_constraint("uq_users_email", "users", type_="unique")
    op.drop_table("users")

    op.drop_constraint("uq_tenants_slug", "tenants", type_="unique")
    op.drop_table("tenants")
